var problems = [
{id: 0, alt: [], name: ""},
{id: 1, alt: [59, 70], name:  "Your house is on fire"},
{id: 2, alt: [70, 71], name:  "Flash flood"},
{id: 3, alt: [56, 82], name:  "It's 20 degrees below zero"},
{id: 4, alt: [55,72], name:  "It120 degrees in the shade"},
{id: 5, alt: [53, 57], name:  "The Man/Woman of Your Dreams is naked next to your bed--smiling..."},
{id: 6, alt: [31, 24], name:  "Your girlfriend is mad at you"},
{id: 7, alt: [52, 57], name:  "Your boss sends you to Hawaii on business"},
{id: 8, alt: [17, 64], name:  "Your Mom is coming over to visit"},
{id: 9, alt: [70, 51], name:  "Mars Attacks!"},
{id: 10, alt: [49, 48], name:  "Imperial Storm Troopers at the door"},
{id: 11, alt: [20, 65], name:  "Texas Hold'em--Pocket Aces"},
{id: 12, alt: [73, 57], name:  "Imperial Fleet Heading Straight at You"},
{id: 13, alt: [20, 65], name:  "Munchies"},
{id: 14, alt: [57, 63], name:  "Heartburn"},
{id: 15, alt: [70, 52], name:  "Caught in a hail storm"},
{id: 16, alt: [51, 61], name:  "Attacked by a Lion"},
{id: 17, alt: [62, 51], name:  "Kitchen Sink too full to use the faucet"},
{id: 18, alt: [17, 62], name:  "Can't find a clean fork"},
{id: 19, alt: [57, 62], name:  "Stressed to the breaking point"},
{id: 20, alt: [57, 53], name:  "Done with work after 14-hour day"},
{id: 21, alt: [50, 13], name:  "Too drunk to stand up"},
{id: 22, alt: [75, 74], name:  "Heading into Death Valley with 1/8 tank"},
{id: 23, alt: [67, 63], name:  "Breaking bathroom scale, pants don't fit"},
{id: 24, alt: [8, 17], name:  "6 friends coming over, nothing in fridge but beer"},
{id: 25, alt: [76, 77], name:  "Toilet backed up"},
{id: 26, alt: [78, 79], name:  "Roaches--lots of them"},
{id: 27, alt: [70, 80], name:  "Choppers--lots of them"},
{id: 28, alt: [48, 70], name:  "4 really big guys with swords coming at you"},
{id: 29, alt: [53, 57], name:  "Late night booty call"},
{id: 30, alt: [47, 65], name:  "Power out--can't see the breaker box"},
{id: 31, alt: [62, 66], name:  "Forgot to pay the gas bill"},
{id: 32, alt: [69, 57], name:  "Internet connection is down!"},
{id: 33, alt: [52, 60], name:  "Girlfriend out of town for 2 weeks"},
{id: 34, alt: [61, 20], name:  "The drums are drowning you out"},
{id: 35, alt: [20, 73], name:  "The guitar is way too loud"},
{id: 36, alt: [68, 63], name:  "Your dog is chasing cars"},
{id: 37, alt: [52, 61], name:  "Dumpster diving for your cell phone"},
{id: 38, alt: [63, 51], name:  "Venereal Disease"},
{id: 39, alt: [70, 51], name:  "Buffalo Charge!"},
{id: 40, alt: [49, 14], name:  "Frozen Hot Pocket"},
{id: 41, alt: [60, 63], name:  "Need Input!"},
{id: 42, alt: [63, 61], name:  "Need data from remote API"},
{id: 43, alt: [61, 57], name:  "Flat Tire"},
{id: 44, alt: [58, 68], name:  "Neighbors having loud sex"},
{id: 45, alt: [51, 73], name:  "Destroy the evidence"},
{id: 46, alt: [57, 62], name:  "Suicide Prevention"},
{id: 47, alt: [53, 9], name:  "Call for an encore"},
{id: 48, alt: [47, 20], name:  "Meet pretty girl in bar"},
{id: 49, alt: [48, 61], name:  "Count Dooku"},
{id: 50, alt: [63, 68], name:  "The Iron Yard, 8:45 am"}
];
