var problems = [
{id: 0, alt: [], name: "", image: "assets/images/ "},
{id: 1, alt: [59, 70],  name:  "Your house is on fire", image: "assets/images/house-on-fire.jpg"},
{id: 2, alt: [70, 71],  name:  "Flash flood", image: "assets/images/flash-floods1.jpg"},
{id: 3, alt: [56, 82],  name:  "It's 20 degrees below zero", image: "assets/images/super-cold-frog.jpg"},
{id: 4, alt: [55,72],  name:  "It120 degrees in the shade", image: "assets/images/hot-weather.jpg"},
{id: 5, alt: [53, 57],  name:  "The Man/Woman of Your Dreams is naked next to your bed--smiling...", image: "assets/images/"},
{id: 6, alt: [31, 24],  name:  "Your girlfriend is mad at you", image: "assets/images/i-am-mad-at-you.jpg"},
{id: 7, alt: [52, 57],  name:  "Your boss sends you to Hawaii on business", image: "assets/images/Hawaii.jpg "},
{id: 8, alt: [17, 64],  name:  "Your Mom is coming over to visit", image: "assets/images/mom.jpg"},
{id: 9, alt: [70, 51],  name:  "Mars Attacks!", image: "assets/images/mars-attacks.jpeg"},
{id: 10, alt: [49, 48],  name:  "Imperial Storm Troopers at the door", image: "assets/images/lego-storm-troopers.jpg"},
{id: 11, alt: [20, 65],  name:  "Texas Hold'em--Pocket Aces", image: "assets/images/Texas-Hold-Em-pocket-aces.jpg"},
{id: 12, alt: [73, 57],  name:  "Imperial Fleet Heading Straight at You", image: "assets/images/Imperial_Fleet_Coruscant.jpg"},
{id: 13, alt: [20, 65],  name:  "Munchies", image: "assets/images/ "},
{id: 14, alt: [57, 63],  name:  "Heartburn", image: "assets/images/heartburn-reflux-1.jpg"},
{id: 15, alt: [70, 52],  name:  "Caught in a hail storm", image: "assets/images/HailStormMan.jpg"},
{id: 16, alt: [51, 61],  name:  "Attacked by a Lion", image: "assets/images/lion_attack.jpg"},
{id: 17, alt: [62, 51],  name:  "Kitchen Sink too full to use the faucet", image: "assets/images/Kitchen-sink-full-of-dirty-dishes.jpg"},
{id: 18, alt: [17, 62],  name:  "Can't find a clean fork", image: "assets/images/dirty-fork.jpg"},
{id: 19, alt: [57, 62],  name:  "Stressed to the breaking point", image: "assets/images/stressed-2.jpg"},
{id: 20, alt: [57, 53],  name:  "Done with work after 14-hour day", image: "assets/images/done-with-work.jpg"},
{id: 21, alt: [50, 13],  name:  "Too drunk to stand up", image: "assets/images/too_drunk_to_karaoke_2.jpg "},
{id: 22, alt: [75, 74],  name:  "Heading into Death Valley with 1/8 tank", image: "assets/images/low_fuel.jpg"},
{id: 23, alt: [67, 63],  name:  "Breaking bathroom scale, pants don't fit", image: "assets/images/fatty.jpg"},
{id: 24, alt: [8, 17],  name:  "6 friends coming over, nothing in fridge but beer", image: "assets/images/friends.jpg"},
{id: 25, alt: [76, 77],  name:  "Toilet backed up", image: "assets/images/toilet.jpg"},
{id: 26, alt: [78, 79],  name:  "Roaches--lots of them", image: "assets/images/roaches.jpeg"},
{id: 27, alt: [70, 80],  name:  "Choppers--lots of them", image: "assets/images/mash.jpg "},
{id: 28, alt: [48, 70],  name:  "4 really big guys with swords coming at you", image: "assets/images/march-w-swords.jpg"},
{id: 29, alt: [53, 57],  name:  "Late night booty call", image: "assets/images/Booty-call.jpg"},
{id: 30, alt: [47, 65],  name:  "Power out--can't see the breaker box", image: "assets/images/power-failure1.jpg"},
{id: 31, alt: [62, 66],  name:  "Forgot to pay the gas bill", image: "assets/images/Gas-bill1.jpg"},
{id: 32, alt: [69, 57],  name:  "Internet connection is down!", image: "assets/images/funny-gif-internet-down.gif"},
{id: 33, alt: [52, 60],  name:  "Girlfriend out of town for 2 weeks", image: "assets/images/frustrated-man.jpg"},
{id: 34, alt: [61, 20],  name:  "The drums are drowning you out", image: "assets/images/Loud-drummer.jpg"},
{id: 35, alt: [20, 73],  name:  "The guitar is way too loud", image: "assets/images/Back-Future.jpg"},
{id: 36, alt: [68, 63],  name:  "Your dog is chasing cars", image: "assets/images/dog_chasing_cars.jpg"},
{id: 37, alt: [52, 61],  name:  "Dumpster diving for your cell phone", image: "assets/images/Dumpster-dive01.jpg"},
{id: 38, alt: [63, 51],  name:  "Venereal Disease", image: "assets/images/venereal.jpg "},
{id: 39, alt: [70, 51],  name:  "Buffalo Charge!", image: "assets/images/buffalo-charging.jpg "},
{id: 40, alt: [49, 14],  name:  "Frozen Hot Pocket", image: "assets/images/hotpockets1.jpg"},
{id: 41, alt: [60, 63],  name:  "Need Input!", image: "assets/images/ShortCircuit2.jpg "},
{id: 42, alt: [63, 61],  name:  "Need data from remote API", image: "assets/images/cloud-API.jpg"},
{id: 43, alt: [61, 57],  name:  "Flat Tire", image: "assets/images/duct-tape.jpg"},
{id: 44, alt: [58, 68],  name:  "Neighbors having loud sex", image: "assets/images/loud-sex.jpg"},
{id: 45, alt: [51, 73],  name:  "Destroy the evidence", image: "assets/images/FORMAT01.jpg"},
{id: 46, alt: [57, 62],  name:  "Suicide Prevention", image: "assets/images/git-push.jpg"},
{id: 47, alt: [53, 9],  name:  "Call for an encore", image: "assets/images/encore.jpg"},
{id: 48, alt: [47, 20],  name:  "Meet pretty girl in bar", image: "assets/images/femme-fatale-cigarette.jpg"},
{id: 49, alt: [48, 61],  name:  "Count Dooku", image: "assets/images/count-dooku.jpg"},
{id: 50, alt: [63, 68],  name:  "The Iron Yard, 8:45 am", image: "assets/images/iron-yard.jpg"}
];
